### ISSUE TITLE
Allow encryption of profiles

### ISSUE THREAD

**Issue by Spunkie** [speedtracker/speedtracker-api#20]
I've been spreading this tool around on various dev communities and a common complaint I hear is that devs don't want to have the urls of the websites/devsites they are testing to be publicly indexable as plaintext in the profiles. Since I believe the url is never saved in the results it seems like a simple solution would be to allow the encryption of the profile files or at a minimum encryption of the url in the profiles.

If you are running a private API the(**untested**) quick fix appears simple, in [SpeedTracker.js - line 318](https://github.com/speedtracker/speedtracker-api/blob/master/lib/SpeedTracker.js#L318) change 
`let url = parameters.url`
to 
`let url = Utils.decrypt(parameters.url, this.options.key)`

This obviously does not take into account the need to maintain backwards compatibility with unencrypted urls on the public API though. It also seems a little odd to me to only allow the encryption of 1 parameter in a profile. So if it's possible allowing encryption of the entire profile file would seem a better option for the public API.

Obvious fallout from this work would be the need to update the documentation on [speedtracker/speedtracker.org](https://github.com/speedtracker/speedtracker.org) and if allowing full profile encryption change the "WHAT DO YOU WANT TO ENCRYPT?" field to a textarea.

**Comment by eduardoboucas** [comment]
I'm not in favour of encrypting the whole file, because you would need to use the decrypt tool every time you want to read anything.

I do agree that it'd be useful to encrypt the URL, and the method you proposed can easily be made backwards compatible by checking if `parameters.url` starts with `http(s)://` — if it does, it means we're dealing with a plain text URL; if it doesn't, we assume the URL is encrypted and so we decrypted before proceeding.

Does that make sense?

**Comment by Spunkie** [comment]
That is pretty simple actually. I was assuming like `example.com` was valid url so I wasn't expecting it to be so easy. If that's true I'll put together a PR for this later.

**Comment by eduardoboucas** [comment]
Looks good to me! I'll set up a dev instance of the API hooked up to the `dev` branch, so we can test this.

**Comment by eduardoboucas** [comment]
Done. Thanks @Spunkie!
